version: "3.9"
services:
  postgres:
    container_name: DB
    image: postgres:14.1-alpine
    environment:
      - PGUSER=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    environment:
      - PORT=5432
      - DB_PASSWORD=root
      - DB_USERNAME=root
      - DB_NAME=test
      - DB_HOST_NAME=postgres
    build: "."
    volumes:
      - ./Backend:/usr/src/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  db:
    driver: local
